@HybridCacheVisualizer.Consumer_HostAddress = https://localhost:7454

GET {{HybridCacheVisualizer.Consumer_HostAddress}}/stampedeSql

###

GET {{HybridCacheVisualizer.Consumer_HostAddress}}/stampedeOldWithStampedeProt

###

GET {{HybridCacheVisualizer.Consumer_HostAddress}}/stampedeOldUnprotected

###

GET {{HybridCacheVisualizer.Consumer_HostAddress}}/stampedeHybridCache

###
