@HybridCacheVisualizer.Consumer_HostAddress = https://localhost:7454

GET {{HybridCacheVisualizer.Consumer_HostAddress}}/stampede/hybridcache

###

GET {{HybridCacheVisualizer.Consumer_HostAddress}}/stampede/protected

###

GET {{HybridCacheVisualizer.Consumer_HostAddress}}/stampede/raw

###

GET {{HybridCacheVisualizer.Consumer_HostAddress}}/stampede/unprotected

###
