@HybridCacheVisualizer.ApiService_HostAddress = https://localhost:7453

@id = 3

###

GET {{HybridCacheVisualizer.ApiService_HostAddress}}/movies/{{id}}/hybridcache

###

GET {{HybridCacheVisualizer.ApiService_HostAddress}}/movies/{{id}}/protected

###

GET {{HybridCacheVisualizer.ApiService_HostAddress}}/movies/{{id}}/raw

###

GET {{HybridCacheVisualizer.ApiService_HostAddress}}/movies/{{id}}/unprotected

###

GET {{HybridCacheVisualizer.ApiService_HostAddress}}/flush

###
